version: '3.3'

services:
   wordpress:
     depends_on:
       - db
     image: sudheer406/mahasatguru
     volumes:
       - wordpress_files:/var/www/html
     ports:
       - "8082:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: 1234

   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 1234
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: 1234
volumes:
    wordpress_files:
    db_data:
